config/routes.rb
Budgeteer::Application.routes.draw do
  
  get "transactions/update"
  root 'accounts#index'
  
  
  get "accounts/index", as: :accounts
  get "accounts/new", as: :new_account
  post "accounts/create", as: :create_account
  get "accounts/:id" => 'accounts#show', as: :show_account
  
  
  get "accounts/:id/upload/new" => 'file_uploads#new', as: :new_file_upload
  post "accounts/:id/upload" => 'file_uploads#create', as: :create_file_upload
  
  
  post "categories/create", as: :create_category
  post "categories/update_transaction"
  
  
  patch "transactions/:id" => 'transactions#update'
  

end

app/models/account.rb
class Account < ActiveRecord::Base
  
  has_many :transactions
  
  def expected_balance
    balance = 0
    Category.roots.each do |cat|
      balance += cat.anticipated_spend_based_on_previous_pay_period(self)
    end
    self.current_balance += balance
  end
  
  
  
end

app/models/bank.rb
class Bank < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  has_ancestry
  
  has_many :transactions
  
  def anticipated_spend_based_on_previous_pay_period(account)
    pay_date_this_month = Date.new(Date.today.year,Date.today.month,Rails.configuration.pay_period_starts)
    ppp_start = (Date.today - 1.month)
    ppp_finish = (pay_date_this_month - (1.month + 1.day))
    ids = self.root? ? self.child_ids : self.id
    ppp_transactions = account.transactions.where(category_id: ids, date: (ppp_start..ppp_finish), one_off: false)
    ppp_transactions.map(&:amount_in_pennies).inject(0,&:+)
  end
  
  def spend_in_previous_pay_period(account)
    pay_date_this_month = Date.new(Date.today.year,Date.today.month,Rails.configuration.pay_period_starts)
    if pay_date_this_month > Date.today
      ppp_start = pay_date_this_month - 2.months
      ppp_finish = pay_date_this_month - 1.month - 1.day
    else
      ppp_start = pay_date_this_month - 1.month
      ppp_finish = pay_date_this_month - 1.day
    end
    ids = self.root? ? self.child_ids : self.id
    ppp_transactions = account.transactions.where(category_id: ids, date: (ppp_start..ppp_finish))
    ppp_transactions.map(&:amount_in_pennies).inject(0,&:+)
  end
  
  def spend_in_current_pay_period(account)
    pay_date_this_month = Date.new(Date.today.year,Date.today.month,Rails.configuration.pay_period_starts)
    if pay_date_this_month > Date.today
      cpp_start = pay_date_this_month - 1.month
      cpp_finish = pay_date_this_month - 1.day
    else
      cpp_start = pay_date_this_month
      cpp_finish = pay_date_this_month + 1.month - 1.day
    end
    ids = self.root? ? self.child_ids : self.id
    cpp_transactions = account.transactions.where(category_id: ids, date: (cpp_start..cpp_finish))
    cpp_transactions.map(&:amount_in_pennies).inject(0,&:+)
  end
  
  def committed_spend_for_pay_period(account)
    pay_date_this_month = Date.new(Date.today.year,Date.today.month,Rails.configuration.pay_period_starts)
    period_start = (Date.today - 1.month)
    period_finish = (pay_date_this_month - 1.month - 1.day)
    ids = self.root? ? self.child_ids : self.id
    cs_transactions = account.transactions.where(category_id: ids, date: (period_start..period_finish), subcategory: ["DIRECTDEBIT","REPEATPMT","DIRECTDEP"])
    cs_transactions.map(&:amount_in_pennies).inject(0,&:+)
  end
  
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  
  belongs_to :account
  belongs_to :category
  
  def root_category
    self.category.root
  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.all
    if @accounts.empty?
      redirect_to new_account_path
    else
    end
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to accounts_path, notice: "Your account has been created."
    else
      flash.now[:error] = @account.errors.full_messages.empty? ? "Unknown error. Please try again" : @account.errors.full_messages.to_sentence
      render action: "new"
    end
  end
  
  def show
    @account = Account.find(params[:id])
    @categories = Category.all
    @root_categories = Category.roots
    @transactions = @account.transactions.includes(:category).paginate(page: params[:page], per_page: 40, order: 'date DESC')
  end
  
  private
  
  def account_params
    params.require(:account).permit(:name,:description,:current_balance)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def create
    category = params[:category]
    transaction = Transaction.find(params[:transaction_id])
    matchdata = /(.*)\bin\b(.*)/.match(category)
    if root = Category.find_by_name(matchdata[2].strip) # If the root category exists, just create the child
      category = root.children.create(name: matchdata[1].strip)
    else # We need to create the root category and then the child category
      root = Category.create(name: matchdata[2].strip)
      category = root.children.create(name: matchdata[1].strip)
    end
    transaction.category = category
    transaction.save
    respond_to do |format|
      format.json {render json: transaction, include: :category}
    end
  end
  
  def update_transaction
    category = Category.find_by_name(params[:category])
    transaction = Transaction.find(params[:transaction_id])
    transaction.category = category
    transaction.save
    respond_to do |format|
      format.json {render json: transaction, include: :category}
    end
  end
  
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  
  def new
    @account = Account.find(params[:id])
  end

  def create
    path = params[:file].tempfile.path
    account = Account.find(params[:id])
    @transactions = Importers::Barclays.import(path,account)
    redirect_to show_account_path(account)
  end
  
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  def update
    @transaction = Transaction.find(params[:id])
    @transaction.update_attributes(transaction_params)
    respond_to do |format|
      format.json {render json: @transaction}
    end
  end
  
  private
  
  def transaction_params
    params.require(:transaction).permit(:payee,:payee_confirmed,:one_off)
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
# encoding: utf-8

module ApplicationHelper
  
  def display(figure)
    if figure > 0
      figure.to_s.insert(-3,".").insert(0,"£")
    elsif figure < 0
      figure.to_s.insert(-3,".").insert(1,"£")
    elsif figure == 0
      figure.to_s.insert(0,"£")
    end
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/create.html.erb
<h1>Accounts#create</h1>
<p>Find me in app/views/accounts/create.html.erb</p>

app/views/accounts/index.html.erb
<div class="row">
	<div class="col-lg-8">
		<h1>Your accounts</h1>
		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Current Balance</th>
				</tr>
			</thead>
			<tbody>
				<% @accounts.each do |a| %>
				<tr>
					<td><%= link_to "#{a.name}", show_account_path(a) %></td>
					<td><%= display(a.current_balance) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/accounts/new.html.erb
<div class="row">
	<div class="col-lg-8">
		<h1>Add a new account</h1>

		<%= semantic_form_for @account, url: create_account_path do |f| %>
	
			<%= f.input :name, input_html: {class: "form-control"} %>
	
			<%= f.input :description, input_html: {class: "form-control"} %>
			
			<li class="string input optional stringish" id="account_current_balance_input"><label class=" label" for="account_current_balance">Current Balance</label>
				<%= f.text_field :current_balance, class: "form-control" %>
			</li>
			
	
			<%= f.action :submit, button_html: {class: "btn btn-primary"} %>
			<%= f.action :cancel, as: :link %>
	
		<% end %>
	</div><!-- eo .col-lg-8 -->
</div><!-- eo .row -->

app/views/accounts/show.html.erb
<div class="row">
	<div class="col-lg-12">
		<h3><%= @account.name %></h3>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<p><%= link_to "Import CSV", new_file_upload_path, class: "btn btn-primary pull-right" %></p>
		<h3>Transactions</h3>
		<table class="table" id="transactions">
			<thead>
				<tr>
					<th>Date</th>
					<th>Description</th>
					<th>Payee</th>
					<th>Category</th>
					<th>Subcategory</th>
					<th>Amount</th>
					<th>Confirmed</th>
					<th>One off</th>
				</tr>
			</thead>
			<tbody>
				<% @transactions.each do |t| %>
				<tr id="transaction-<%= t.id %>">
					<td><%= t.date.strftime("%d %b %Y") %></td>
					<td><%= t.description %></td>
					<td class="payee"><%= t.payee %></td>
					<% if t.category.nil? %>
						<td class="input-holder"><%= text_field_tag 'category[name]', t.category.try(:name), id: "category_name_#{t.id}", class: "category_name form-control" %></td>
					<% else %>
						<td class="category-name-holder"><%= t.category.name %></td>
					<% end %>
					<td><%= t.subcategory %></td>
					<td><%= display(t.amount_in_pennies) %></td>
					<td><%= check_box_tag "transaction_#{t.id}_confirmed", t.payee_confirmed? ? "yes" : "no", t.payee_confirmed?, class: "confirm-transaction" %></td>
					<td><%= check_box_tag "transaction_#{t.id}_one_off", t.one_off? ? "yes" : "no", t.one_off?, class: "one-off-transaction" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<%= will_paginate @transactions %>
	</div><!-- eo .col-lg-12 -->
</div><!-- eo .row -->

<div class="row">
	<div class="col-lg-4">
		<h3>Current balance: <%= display(@account.current_balance) %></h3>
	</div>
	<div class="col-lg-4">
		<h3>Expected balance: <%= display(@account.expected_balance) %></h3>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<table>
			<thead>
				<tr>
					<th>Category</th>
					<th>Spend in last pay period</th>
					<th>Spend to date this pay period</th>
					<th>Anticipated spend before pay day based on last pay period</th>
					<th>Committed spend before pay day this period</th>
					<th>Expected further spend before pay day</th>
				</tr>
			</thead>
			<tbody>
				<% @root_categories.each do |cat| %>
				<tr class="root-category">
					<td><%= cat.name %></td>
					<td><%= display(cat.spend_in_previous_pay_period(@account)) %></td>
					<td><%= display(cat.spend_in_current_pay_period(@account)) %></td>
					<td><%= display(cat.anticipated_spend_based_on_previous_pay_period(@account) - cat.committed_spend_for_pay_period(@account)) %></td>
					<td><%= display(cat.committed_spend_for_pay_period(@account)) %></td>
					<td><%= display(cat.anticipated_spend_based_on_previous_pay_period(@account)) %></td>
				</tr>
				<% cat.children.each do |sub| %>
				<tr class="sub-category">
					<td><%= sub.name %></td>
					<td><%= display(sub.spend_in_previous_pay_period(@account)) %></td>
					<td><%= display(sub.spend_in_current_pay_period(@account)) %></td>
					<td><%= display(sub.anticipated_spend_based_on_previous_pay_period(@account) - sub.committed_spend_for_pay_period(@account)) %></td>
					<td><%= display(sub.committed_spend_for_pay_period(@account)) %></td>
					<td><%= display(sub.anticipated_spend_based_on_previous_pay_period(@account)) %></td>
				</tr>
				<% end %>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

<ol id="category-list">
	<% Category.roots.sort_by(&:name).each do |c| %>
	<li id="category-<%= c.id %>" class="root category"><%= c.name %></li>
	<ol>
	<% c.children.sort_by(&:name).each do |child| %>
		<li id="category-<%= c.id %>" class="sub category"><%= child.name %></li>
	<% end %>
	</ol>
	<% end %>
</ol>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/file_uploads/create.html.erb
<h1>FileUploads#create</h1>
<p>Find me in app/views/file_uploads/create.html.erb</p>

app/views/file_uploads/new.html.erb
<div class="row">
	<div class="col-lg-8">
		<h2>Upload your file</h2>

		<%= form_tag "/accounts/#{@account.id}/upload", :multipart => true do %>

			<label for="file">Choose a file:</label>
			<%= file_field_tag "file", class: "form-control" %>

			<p><%= submit_tag "Upload", class: "btn btn-primary" %></p>

		<% end %>
	</div><!-- eo .col-lg-8 -->
</div><!-- eo .row -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budgeteer</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">

		<%= yield %>

	</div><!-- eo .container -->
</body>
</html>

app/views/transactions/update.html.erb
<h1>Transactions#update</h1>
<p>Find me in app/views/transactions/update.html.erb</p>